<a href="https://colab.research.google.com/github/Fayikk/NUMPY_Basics/blob/master/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np # takma isim için as takısı kullandık

#python list
py_list=[1,2,3,4,5,6,7,8,9]
#nump array
result=np.array([1,2,3,4,5,6,7,8,9]) #burada dizimizi hazır hale getiriyoruz.
result.ndim #Burada ise dizimizin boyutunu göstermektedir.
print(type(result))#numpy üzerinden oluşturduğumuz dizi npArray'dir

<class 'numpy.ndarray'>


In [13]:
py_multi=[[1,2,3],[4,5,6],[7,8,9]]

In [20]:
#reshape() metodu ile şekillendirme işlemi
np_multi=result.reshape(3,3)
np_multi
print(np_multi.ndim)#Dimension=boyut anlamına gelmektedir.

np_multi.shape #shape metodu ile np_multi arrayinin 3'e 3'lük bir matris olduğunu bize söylemektedird.

2


(3, 3)

In [27]:
import numpy as np
# result=np.array([1,3,5,7,9])
#elemanları kendimiz belirtmek istemezsek arange() metodunu kullanacağız
# result=np.arange(1,10)#1 dahil ancak 10 dahil olmadan oluşturulan array'i görüyoruz:
# result=np.arange(1,100,3) #Burada ise adım sayısnı kendimiz belirtebiliiriz:Burada 3er adım ile 100'e kadar gitmesini beklemekteyiz.
# result=np.zeros(10)  #0'lardan oluşan bir dizi karşımıza gelmektedir.
result=np.ones(10)#1'lerden oluşan bir array karşımıza gelmektedir.Bunlar görüldüğü üzere float tiptedirler.
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
# result=np.linspace(0,100,5) #linespace() metodu ile 0 ile 100 arasnın 5 eşit parçayı bölmek isteriz.Buda float tipindedir.Double değer ataması yapılabilmektedir.

result=np.linspace(1,5,5)
result

array([1., 2., 3., 4., 5.])

In [35]:
result=np.random.randint(1,50)#1 ile 50 arasında rastgele sayı üretemeyi sağladık.
result

37

In [36]:
result=np.random.randint(1,10,3) #1 ile 10 arasında rastgele üretilmiş 3 sayı ekrana yazdırmaktadır:
result

array([6, 7, 7])

In [38]:
result=np.random.rand(5) #random'dan gelen rand metodu ile 0 ile 1 değerleri arasında 5 farklı değer üretimi yapacaktır:

result

array([0.44233888, 0.37997569, 0.29888638, 0.71124972, 0.93974883])

In [42]:
np_array=np.arange(50)
result=np_array.reshape(5,10) # 5'e 10'luk bir matris oluşturmuş oluyoruz.
result

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
result=np.random.randint(1,100,10)
result1=result.max() #max() komutu ile oluşturulan sayılar arasında bir en büyük sayıyı ekrana yazdırmaktadır.
result2=result.min() #min() en küçük değeri ekrana yazıdrmaktadır.
result1
# result2

95

In [123]:
result=np.random.randint(1,100,10)
print(result)
# result1=result.argmax() #argmax komutu ile üretilen en büyük sayının kaçıncı indekste olduğuna karar veren yapıdır.
result1=result.argmin() #burada ise üretilen minimum sayının indeks'ini görmekteyiz. 
result1

[76 84 17 11 20 81 81 55 49 37]


3

#NUMPY DİZİLERİNİN İNDEKSLENMESİ

In [56]:
import numpy as np
numbers=np.array([0,5,10,15,20,25,50,75])
result=numbers[5] #5.indis'teki değeri tutar
result=numbers[:3] # 0 dan başlayıp 3.indeksteki değere kadar girn yapıdır.
result

array([ 0,  5, 10])

In [71]:
numbers=np.array([[0,5,10,100],[15,20,25,105],[50,75,100,110]])
result=numbers[0]
result=numbers[0][2] #0.ideksteki satırın,2.sütun'undaki elemanın değelerini ekrana yazdırır.
result=numbers[:,2] # her satırın 2.indeksteki elemanlarını ekrana yazdıran programdır.
result=numbers[:,0] # "     "     0. indeksteki elemanları ekrana yazdıran programdır.
result=numbers[:,1:3] #1.indeks dahil olmadan 3.indekse kadar olan kısımları alıp ekrana yazdıralım.
result=numbers[:2,:2] #ilk 2 satır ve 2 sütun değerini ekrana yazdıran programdır.
result

array([[ 0,  5],
       [15, 20]])

In [74]:
#Referans kopyalamsı işlemlerini gerçekleştirmiş olduk.
arr1=np.arange(0,10)
arr2=arr1
arr2[0]=100
arr1
arr2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [79]:
#ŞİMDİ İSE copy() metoduna bakalım.
arr1=np.arange(1,11)
arr2=arr1.copy()
arr2[0]=98 #görüldüğü üzere arr2'nin 0.indisli elemanına 98 değer atamasını yapmış olduk.Ancak copy() metodu ile yer tutucuları birbirinden ayırdığımzı için ikisi içinde yapılan.
#değişikliklerden arr2 ve arr1 etkilenmeyecektir
arr1 #yazdırma işlemi yapıldığında arr1 0.indisli elemanın 98 olmadığını görebiliriz.


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#NUMPY DİZİ OPERASYONLARI

In [80]:
import numpy as np

In [89]:
numbers=np.random.randint(10,100,6)
numbers2=np.random.randint(10,100,6)
print(numbers)
print(numbers2)
result=numbers+numbers2 #dizinin elemanlarını indis sıralarına göre toplamaktadır.
result2=numbers-numbers2
print("arrayler arasındaki fark: {}".format(result2))
print("arrayler arasındaki toplam değer: {}".format(result))
print("arraylerin birbirleri capimi: ",result*result2)
print("arraylerin birbirleri ile bolümü: ",result/result2) #bölüm işleminde değişken tiplerinde dolayı problem oluşabilir.

[89 32 82 93 78 38]
[55 37 30 68 51 89]
arrayler arasındaki fark: [ 34  -5  52  25  27 -51]
arrayler arasındaki toplam değer: [144  69 112 161 129 127]
arraylerin birbirleri capimi:  [ 4896  -345  5824  4025  3483 -6477]
arraylerin birbirleri ile bolümü:  [  4.23529412 -13.8          2.15384615   6.44         4.77777778
  -2.49019608]


In [96]:
#Herhangi bir dizinin trigonometrik değerlerini almak istyoruz.
result=np.sin(numbers)
print("cosinus degeri: ",np.cos(numbers))
print("tanjant degeri: ",np.tan(numbers))
# print("cotanjant degeri: ",np.cot(numbers))

#KAREKÖKLERİNİ ALMAK İÇİN
result=np.sqrt(numbers)
result

cosinus degeri:  [ 0.51017704  0.83422336  0.9496777   0.3174287  -0.85780309  0.95507364]
tanjant degeri:  [ 1.68582537  0.66100604  0.32982641 -2.98738626 -0.59918     0.31030966]


array([9.43398113, 5.65685425, 9.05538514, 9.64365076, 8.83176087,
       6.164414  ])

In [105]:
mnumbers1=numbers.reshape(2,3)
mnumbers2=numbers2.reshape(2,3)

print(mnumbers1)
print("********")
print(mnumbers2)

[[89 32 82]
 [93 78 38]]
********
[[55 37 30]
 [68 51 89]]


In [111]:
#Matrisleri birbirleri ile dikey olarak birleştirme işlemi yapalım.
result=np.vstack((mnumbers1,mnumbers2)) #vstack metodu ile iki farklı matris'i dikey(vertical) olarak birleştirme işlemi yapar,satır sayısını arttırmış olacaktır.
result

array([[89, 32, 82],
       [93, 78, 38],
       [55, 37, 30],
       [68, 51, 89]])

In [113]:
#Matrisleri birbirleri ile yatay olarak birleştirme işlemi yapalım.
result=np.hstack((mnumbers1,mnumbers2)) #hstack metodu ile iki farklı matris'i yatay(horizantal) olarak birleştirme işlemi yapar,sütun sayısını arttırmış olacaktır.
result

array([[89, 32, 82, 55, 37, 30],
       [93, 78, 38, 68, 51, 89]])

In [122]:
mynumbers=np.arange(10,100,3)
result=mynumbers>=50 #mynumbers listesindeki değerler 50'den büyük eşitmidir.
division=mynumbers%2==0

print(mynumbers)
print("*********")
print(result)
print("*********")
print(division)
print("************")
print(mynumbers[division]) #yukarıda division değerin 2'ye bölünebilen değrleri indeks şeklinde yazdırmasını gerçekleştirirsek.
#2'ye bölünebilen değerlleri ekranda yazdıracaktır:

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]
*********
[False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
*********
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False]
************
[10 16 22 28 34 40 46 52 58 64 70 76 82 88 94]
