<a href="https://colab.research.google.com/github/Fayikk/NUMPY_Basics/blob/master/Numpy_Applications.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY PEKİŞTİRMEK AÇISINDAN UYUGULAMA YAPALIM

In [21]:
import numpy as np
#1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
my_numpy=np.array([10,15,30,45,60])
my_numpy

array([10, 15, 30, 45, 60])

In [25]:
#2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
result=np.arange(5,16)
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
#3- (50-100) arasında 5'er 5'er artarak numpy dizisini oluşturunuz.
result=np.arange(50,101,5)
result

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100])

In [28]:
#4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
result=np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
#5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
result=np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
#6- (0-100) arasında eşit aralıklı 5 sayı üretin
# numbers=np.arange(0,101)

numbers=np.linspace(0,100,5)
numbers


array([  0.,  25.,  50.,  75., 100.])

In [43]:
#7- (10-30) arasında rastgele 5 tane tamsayı üretin.
result=np.random.randint(10,30,5)
result

array([11, 10, 20, 26, 19])

In [45]:
#8- [-1 ile 1] arasında 10 adet sayı üretin
result=np.random.random(10)
result

array([0.67601778, 0.39120336, 0.91546461, 0.00685515, 0.43168327,
       0.95649579, 0.3376016 , 0.87926409, 0.22157037, 0.25803327])

In [50]:
#9- (3X5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz. 
my_array=np.random.randint(10,50,15)
result=my_array.reshape(3,5)
result

array([[34, 10, 12, 38, 38],
       [27, 36, 20, 12, 45],
       [17, 14, 19, 33, 22]])

In [10]:
 #10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız.

In [53]:
#11-Üretilen matrisin en büyük ve en küçük ortalaması nedir?
result=my_array.max()
result1=my_array.min()
print(result)
print(result1)

45
10


In [54]:
#12- Üretilen matrisin en büyük değerinin indeksi kaçtır?
resultt=my_array[result1]
resultt

17

In [55]:
#13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
my_list=np.arange(10,21)
my_list

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
#14- Üretilen dizinin elemanlarını tersten yazdırın.
print(reversed(my_array))

In [87]:
#15- Üretilen matrisin ilk satırını seçiniz.
my_array=np.random.randint(10,50,15)
result=my_array.reshape(3,5)
result1=result[0]#ilk satır için gerekli kod bloğu
print(result)
result1

[[33 38 49 15 40]
 [21 15 33 33 13]
 [34 23 22 10 16]]


array([33, 38, 49, 15, 40])

In [88]:
#16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir?
result3=result[1][2]
print(result3)

33


In [89]:
#17-Üretilen matrisin tüm satırlardaki ilk elemanın seçiniz.
result[:]

array([[33, 38, 49, 15, 40],
       [21, 15, 33, 33, 13],
       [34, 23, 22, 10, 16]])

In [95]:
#18-Üretilen matrisin her bir elemanın karesini alınız.
result4=np.sqrt(result)
result4


array([[5.74456265, 6.164414  , 7.        , 3.87298335, 6.32455532],
       [4.58257569, 3.87298335, 5.74456265, 5.74456265, 3.60555128],
       [5.83095189, 4.79583152, 4.69041576, 3.16227766, 4.        ]])

In [100]:
#19-Üretilen matris elemanlarının hangisi pozitif çift sayıdır?Aralığı (-50,+50) arasında yapınız.
my_Array=np.arange(-50,51,2)
result=my_Array>0
print(result)
print("*******")
print(my_Array[result])

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]
*******
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
